#!/usr/bin/env bash
# Generate Fusion Pixel (像素缝合) LVGL bitmap fonts for qzos.
#
# Font policy (see brain: qzos-ui-architecture): pixel fonts only, 1bpp,
# no antialiasing, no vector fonts (Montserrat etc. are disabled in lv_conf.h).
#
# Requires: node/npx (lv_font_conv), python3 (symbols), downloaded TTF zips.
# Symbols: os/fonts/symbols.txt (generated by gen_symbols.py).
#
# Usage: scripts/gen-fonts.sh [8|10|12 ...]   (default: all present sizes)
set -euo pipefail
cd "$(dirname "$0")/.."
FDIR=os/fonts
SYMBOLS="$FDIR/symbols.txt"

# TTF locations (override with FUSION_TTF_<size>). The release zips ship
# locale variants; zh_hans covers latin+CJK (GB2312 一级汉字 ⊂ zh_hans),
# so prefer it over the -latin/-ja/-ko variants.
ttf_for() {
  local size=$1
  local f
  for f in \
    "${FUSION_TTF_${size}:-}" \
    "/tmp/fusion-pixel/fusion-pixel-${size}px-monospaced-ttf/fusion-pixel-${size}px-monospaced-zh_hans.ttf" \
    "/tmp/fusion-pixel/fusion-pixel-${size}px-monospaced-ttf/ttf/fusion-pixel-${size}px-monospaced-zh_hans.ttf"
  do
    [ -n "$f" ] && [ -f "$f" ] && { echo "$f"; return 0; }
  done
  return 1
}

gen_one() {
  local size=$1
  local ttf
  if ! ttf=$(ttf_for "$size"); then
    echo "skip ${size}px: ttf not found (download fusion-pixel-font-${size}px-monospaced-ttf zip first)" >&2
    return 1
  fi
  local out="$FDIR/fusion_pixel_${size}.c"
  echo "gen $out  (ttf: $ttf)"
  # NOTE: --autohint-off must come AFTER --font (lv_font_conv arg parsing).
  npx --yes lv_font_conv \
    --bpp 1 \
    --size "$size" \
    --font "$ttf" \
    --autohint-off \
    --symbols "$(cat "$SYMBOLS")" \
    --format lvgl \
    --lv-font-name "fusion_pixel_${size}" \
    --no-compress \
    -o "$out"
  echo "  -> $(wc -c < "$out") bytes"
}

sizes=("$@")
if [ ${#sizes[@]} -eq 0 ]; then
  sizes=(12 10 8)
fi
fail=0
for s in "${sizes[@]}"; do
  gen_one "$s" || fail=1
done
exit $fail
